default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: <%= ENV["TANKS_DB_HOST"] %>
  username: <%= ENV["TANKS_DB_USER"] %>
  password: <%= ENV["TANKS_DB_PASS"] %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: auth_database

production:
  <<: *default
  database: auth_production
  username: auth
  password: <%= ENV['AUTH_DATABASE_PASSWORD'] %>
