default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: auth_development
 
production:
  <<: *default
  database: auth_production
  username: auth
  password: <%= ENV['AUTH_DATABASE_PASSWORD'] %>
